baseURL = 'https://andrescheca.github.io/clases/'
languageCode = 'en-us'
title = 'Diapositivas para clases'
theme = ["github.com/dzello/reveal-hugo"]

[params.reveal_hugo]
custom_theme = "css/uees.css"
highlight_theme = "catppuccin-frappe"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[author]
name = "Andrés Checa"

[params.author]
name = "Andrés Checa"
email = "achecapalacios@uees.edu.ec"

[markup.highlight]
codeFences = false  # use highlight.js
# codeFences = true  # use hugo highlighting at compile time
style = "catppuccin-frappe"
